version: '3.9'

services:
  ai_services:
    build: ./ai_services
    env_file:
      - ./ai_services/.env
    ports:
      - "8002:8000"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9000"   # External 9002 -> Internal 9000
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=root
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
      - ./vault/logs:/vault/logs

volumes:
  minio_data:
